#!/bin/sh

#CONKY_EXEC="$(command -v conky)"
if [[ $(xrandr --listmonitors | awk '$1 ~ /Monitor/ {print $2}') ]]; then
	conky -q -c $HOME/.local/share/dwm/conky/conky_time
	conky -q -c $HOME/.local/share/dwm/conky/conky.conf
fi
#if [ -z $CONKY_EXEC ]; then
	while true; do
		$HOME/.local/share/dwm/dwm-bar-refresh
		sleep 2
	done
#fi

if [ -n $CONKY_EXEC ]; then
	$CONKY_EXEC | \
		while read LINE; do xsetroot -name "$LINE"; done
fi
